import { appendFile } from "node:fs/promises";
import { diffDocuments, fetchOpenApi } from "../src/schema-diff.js";
import { loadOpenApiDocument } from "../src/openapi.js";

const diff = diffDocuments(await loadOpenApiDocument(), await fetchOpenApi());
const list = (values: string[]) =>
  values.length ? values.map((value) => `- \`${value}\``).join("\n") : "- None";
const body = [
  "The upstream EVE Online ESI OpenAPI document differs from the pinned schema.",
  "",
  `Pinned SHA-256: \`${diff.currentHash}\``,
  `Upstream SHA-256: \`${diff.upstreamHash}\``,
  "",
  `### Added operations (${diff.added.length})`,
  list(diff.added),
  "",
  `### Removed operations (${diff.removed.length})`,
  list(diff.removed),
  "",
  `### Modified operations (${diff.modified.length})`,
  list(diff.modified),
  "",
  "Run `npm run schema:update` in the eve-online-mcp devcontainer to update `lib/openapi/esi-openapi.json`. Review the schema diff and compatibility impact, including every changed non-GET operation. Publish the reviewed eve-online-mcp-lib commit first, then update the lib submodule pointer, tests and implementation in eve-online-mcp and close this issue in that pull request.",
  "",
  "This issue was generated by the scheduled ESI schema monitor.",
].join("\n");

console.log(diff.changed ? body : "Pinned ESI OpenAPI schema is current.");
if (process.env.GITHUB_OUTPUT) {
  const delimiter = `ESI_SCHEMA_${Date.now()}`;
  await appendFile(
    process.env.GITHUB_OUTPUT,
    [
      `changed=${String(diff.changed)}`,
      `upstream_hash=${diff.upstreamHash}`,
      `body<<${delimiter}`,
      body,
      delimiter,
      "",
    ].join("\n"),
    "utf8",
  );
}
if (diff.changed && process.argv.includes("--fail-on-change"))
  process.exitCode = 1;
